---
#
# For more information see: https://gethomepage.dev/latest/configs/bookmarks
#

- Links:
    - GitHub:
        - icon: git.svg
          href: https://github.com/scottgigawatt
          description: GitHub Projects ğŸ™

    - Hera:
        - icon: synology-dsm.svg
          href: https://{{HOMEPAGE_VAR_HOST_URL}}
          description: Gateway to the Gods ğŸ›ï¸

    - Codex:
        - icon: mkdocs.svg
          href: https://{{HOMEPAGE_VAR_WIKI_URL}}
          description: Wisdom of the Stars ğŸŒŸâœ¨

    - Cetus:
        - icon: synology-dsm.svg
          href: https://{{HOMEPAGE_VAR_DSM2_URL}}
          description: Portal to the Abyss ğŸŒŠ
