---
#
# For more information see: https://gethomepage.dev/latest/configs/bookmarks
#

- Credits:
    - Duplex:
        - icon: github.svg
          href: https://github.com/scottgigawatt/duplex
          description: Docker Utilities for Plex on Synology DSM ğŸ¿

    - Plundarr:
        - icon: github.svg
          href: https://github.com/scottgigawatt/plundarr
          description: Docker Compose for media 'arr' tools + PIA WireGuard VPN ğŸ´â€â˜ ï¸

    - Privateerr:
        - icon: github.svg
          href: https://github.com/scottgigawatt/privateerr
          description: Docker Compose for PIA + WireGuard âš“ï¸

- Synology:
    - Hera:
        - icon: synology-dsm.svg
          href: https://{{HOMEPAGE_VAR_HOST_URL}}
          description: Gateway to the Gods ğŸ›ï¸

    - Cetus:
        - icon: synology-dsm.svg
          href: https://{{HOMEPAGE_VAR_DSM2_URL}}
          description: Portal to the Abyss ğŸŒŠ

    - Meow-thership:
        - icon: synology-dsm.svg
          href: https://{{HOMEPAGE_VAR_DSM3_URL}}
          description: Space Cat World Domination ğŸ±ğŸš€

- Links:
    - Trakt:
        - icon: trakt.svg
          href: https://trakt.tv/dashboard
          description: Track. Discover. Share. ğŸ¬ğŸŒŸ

    - Codex:
        - icon: mkdocs.svg
          href: https://{{HOMEPAGE_VAR_HOST_URL}}
          description: Wisdom of the Stars ğŸŒŸâœ¨

    - LinuxServer.io:
        - icon: linuxserver-io.svg
          href: https://docs.linuxserver.io/
          description: Where 'Arr' Apps Set Sail for Smooth Seas and Safe Harbors! ğŸ´â€â˜ ï¸

- Social:
    - Reddit:
        - icon: reddit.svg
          href: https://reddit.com/
          description: The front page of the internet ğŸŒğŸ‘¾

    - TikTok:
        - icon: tiktok.svg
          href: https://www.tiktok.com/
          description: Make every second count â³ğŸµ
