---
#
# For more information see: https://gethomepage.dev/latest/configs/bookmarks
#

- Links:
    - GitHub:
        - icon: si-github.png
          href: https://github.com/scottgigawatt
          description: GitHub Projects ğŸ™

    - Hera:
        - icon: si-synology-dsm.png
          href: https://{{HOMEPAGE_VAR_HOST_URL}}
          description: Gateway to the Gods ğŸ›ï¸

    - Cetus:
        - icon: si-synology-dsm.png
          href: https://{{HOMEPAGE_VAR_DSM2_URL}}
          description: Portal to the Abyss ğŸŒŠ

    - Codex:
        - icon: si-mkdocs.svg
          href: https://{{HOMEPAGE_VAR_WIKI_URL}}
          description: Wisdom of the Stars ğŸŒŸâœ¨
