---
#
# For more information see: https://gethomepage.dev/latest/configs/settings
#

title: {{HOMEPAGE_VAR_TITLE}}
favicon: /images/icons/peacock-feather-gradient.png

color: slate

background: /images/backgrounds/electric-sphere.gif
#  blur: sm
#  saturate: 50
#  brightness: 75
#  opacity: 75

cardBlur: md
headerStyle: boxedWidgets
useEqualHeights: true
disableCollapse: true
hideVersion: false
showStats: true
statusStyle: "dot"
target: _blank

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Media:
    style: row
    columns: 3

  Data:
    style: row
    columns: 2

  Downloads:
    style: row
    columns: 3

  Links:
    style: row
    columns: 2
