blank_issues_enabled: false

contact_links:
  - name: ðŸ”¥HADESðŸ”¥
    url: https://discord.gg/BpEGzWwGYf
    about: If your code be screaming like the damned, step past the â›§ gates â›§ and call upon the underworld crew for guidance
